---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink
  labels:
    app: sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sink
  template:
    metadata:
      labels:
        app: sink
    spec:
      containers:
      - name: sink
        image: khinkali/sink:0.0.1
        env:
        - name: KAFKA_ADDRESS
          value: "kafka:9092"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sink
spec:
  selector:
    app: sink
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081
  type: NodePort
